
    FROM openjdk:17-jdk-buster
    USER root
    ADD aaas
    RUN mv /opt/aaas /opt/smartops-application
    RUN chmod 777 -R /opt/smartops-application
    EXPOSE 8083:8083
    CMD ["/opt/smartops-application/bin/catalina.sh","run"]
    